<a class="action primary" href="<?php echo $block->getUrl('helloworld/index/insert'); ?>">Add Record</a>
<table>
     <tr>
          <th>Id</th>
          <th>Image</th>
          <th>Name</th>
          <th>URL</th>
          <th>Tag</th>
          <th>Created At</th>
          <th>Updated At</th>
          <th colspan="2">Action</th>
     </tr>
 
     <?php
          $collection = $block->getResult();
          foreach($collection as $item){
     ?>
     
     <tr>
          <td><?php echo $item->getData('post_id'); ?></td>
          <td><img width="50px" height="50px" src="<?php echo $item->getData('featured_image'); ?>" alt=""></td>
          <td><?php echo $item->getData('name'); ?></td>
          <td><?php echo $item->getData('url_key'); ?></td>
          <td><?php echo $item->getData('tags'); ?></td>
          <td><?php echo $item->getData('created_at'); ?></td>
          <td><?php echo $item->getData('updated_at'); ?></td>
          <td><a href="<?php echo $block->getUrl('helloworld/index/edit').'id/'.$item->getData('post_id'); ?>" class="action primary">Edit</a></td>
          <td><a onclick="return confirm('Are you sure?')" href="<?php echo $block->getUrl('helloworld/index/delete').'?id='.$item->getData('post_id'); ?>" class="action primary">Delete</a></td>
     </tr>
     <?php } ?>
</table>